/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */

//define the DB
exports.up = async function (knex) {
    //new extention that generats unique ids
    await knex.raw('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
    //edit schema
    return knex.schema
//-------------------------------------------------------------------------------------------
    /**
     * knex.schema.createTable(table_name, function(table){ ATT #1; ATT #2; ATT #3; ATT #4});
     */
//-------------------------------------------------------------------------------------------
    //new table named 'debates' (table_name, function contains the content of the table)
    .createTable('debates',
        function(table){
            //ATT #1 create unique id ((generated by the uuid function)) - name of att - PK - NOT NULL - generate unique id
            table.uuid('id').primary().notNullable()
            .defaultTo(knex.raw('uuid_generate_v1()'));
            //ATT #2 - NOT NULL - UNIQUE
            table.string('title').notNullable().unique();
            //ATT #3 
            table.string('descripttion');
            //ATT #4 - with default time (current time)
            table.timestamp('created_at').defaultTo(knex.fn.now());
        }
    );
};
  
  /**
   * @param { import("knex").Knex } knex
   * @returns { Promise<void> }
   */
exports.down = function (knex) {


};